my_cartesian_motion_controller:
    type: "position_controllers/CartesianMotionController"
    end_effector_link: "tm_tip_link"
    robot_base_link: "base_link"
    target_frame_topic: "target_frame"
    joints:
    - tm_shoulder_1_joint
    - tm_shoulder_2_joint
    - tm_elbow_1_joint
    - tm_wrist_1_joint
    - tm_wrist_2_joint
    - tm_wrist_3_joint

    pd_gains:
        trans_x: {p: 5.0}
        trans_y: {p: 5.0}
        trans_z: {p: 5.0}
        rot_x: {p: 1.0}
        rot_y: {p: 1.0}
        rot_z: {p: 1.0}
    solver:
        error_scale: 0.02
        
my_cartesian_force_controller:
    type: "position_controllers/CartesianForceController"
    end_effector_link: "tm_tip_link"
    robot_base_link: "base_link"
    ft_sensor_ref_link: "tm_tip_link"
    joints:
    - tm_shoulder_1_joint
    - tm_shoulder_2_joint
    - tm_elbow_1_joint
    - tm_wrist_1_joint
    - tm_wrist_2_joint
    - tm_wrist_3_joint

    pd_gains:
        trans_x: {p: 0.02}
        trans_y: {p: 0.0}
        trans_z: {p: 0.0}
        rot_x: {p: 0.0}
        rot_y: {p: 0.0}
        rot_z: {p: 0.0}
    solver:
        error_scale: 1.0

my_cartesian_compliance_controller:
    type: "position_controllers/CartesianComplianceController"
    end_effector_link: "tm_tip_link"    # All links below must come before this link
    robot_base_link: "base_link"
    ft_sensor_ref_link: "tm_tip_link"
    compliance_ref_link: "tm_tip_link"
    target_frame_topic: "target_frame"
    joints:
    - tm_shoulder_1_joint
    - tm_shoulder_2_joint
    - tm_elbow_1_joint
    - tm_wrist_1_joint
    - tm_wrist_2_joint
    - tm_wrist_3_joint

    stiffness:  # w.r.t. compliance_ref_link
        trans_x: 500
        trans_y: 500
        trans_z: 500
        rot_x: 100
        rot_y: 100
        rot_z: 100

    pd_gains:
        trans_x: {p: 0.01}
        trans_y: {p: 0.01}
        trans_z: {p: 0.01}
        rot_x: {p: 0.06}
        rot_y: {p: 0.06}
        rot_z: {p: 0.06}
    solver:
        error_scale: 0.02

my_motion_control_handle:
   type: "cartesian_controllers/MotionControlHandle"
   end_effector_link: "tm_tip_link"
   robot_base_link: "base_link"
   target_frame_topic: "target_frame"
   joints:
    - tm_shoulder_1_joint
    - tm_shoulder_2_joint
    - tm_elbow_1_joint
    - tm_wrist_1_joint
    - tm_wrist_2_joint
    - tm_wrist_3_joint

# my_joint_to_cartesian_controller:
#     type: "cartesian_controllers/JointControllerAdapter"
#     end_effector_link: "tm_tip_link"
#     robot_base_link: "base_link"
#     target_frame_topic: "target_frame"
#     joints:
#     - tm_shoulder_1_joint
#     - tm_shoulder_2_joint
#     - tm_elbow_1_joint
#     - tm_wrist_1_joint
#     - tm_wrist_2_joint
#     - tm_wrist_3_joint

#     joint_limits:
#       joint1:
#         has_velocity_limits: true
#         max_velocity: 3.15
#         has_acceleration_limits: true
#         max_acceleration: 10.0
#       joint2:
#         has_velocity_limits: true
#         max_velocity: 3.15
#         has_acceleration_limits: true
#         max_acceleration: 10.0
#       joint3:
#         has_velocity_limits: true
#         max_velocity: 3.15
#         has_acceleration_limits: true
#         max_acceleration: 10.0
#       joint4:
#         has_velocity_limits: true
#         max_velocity: 3.2
#         has_acceleration_limits: true
#         max_acceleration: 10.0
#       joint5:
#         has_velocity_limits: true
#         max_velocity: 3.2
#         has_acceleration_limits: true
#         max_acceleration: 10.0
#       joint6:
#         has_velocity_limits: true
#         max_velocity: 3.2
#         has_acceleration_limits: true
#         max_acceleration: 10.0

# my_joint_to_cartesian_controller/joint_trajectory_controller:
#     type: "position_controllers/JointTrajectoryController"
#     joints:
#     - tm_shoulder_1_joint
#     - tm_shoulder_2_joint
#     - tm_elbow_1_joint
#     - tm_wrist_1_joint
#     - tm_wrist_2_joint
#     - tm_wrist_3_joint

joint_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
    - tm_shoulder_1_joint
    - tm_shoulder_2_joint
    - tm_elbow_1_joint
    - tm_wrist_1_joint
    - tm_wrist_2_joint
    - tm_wrist_3_joint

joint_state_controller:
    type: joint_state_controller/JointStateController
    joints:
    - tm_shoulder_1_joint
    - tm_shoulder_2_joint
    - tm_elbow_1_joint
    - tm_wrist_1_joint
    - tm_wrist_2_joint
    - tm_wrist_3_joint
    publish_rate: 50